WITH RankedStates AS (
  SELECT
    STATE,
    DISTRICT_TYPE,
    RANK() OVER (PARTITION BY DISTRICT_TYPE ORDER BY SUM(CASES) DESC) AS rank_by_cases,
    RANK() OVER (PARTITION BY DISTRICT_TYPE ORDER BY SUM(DEATHS) DESC) AS rank_by_deaths
  FROM RKI_GER_COVID19_DASHBOARD
  GROUP BY STATE, DISTRICT_TYPE
)

SELECT
  STATE,
  DISTRICT_TYPE,
  MAX(CASES) AS total_cases,
  MAX(DEATHS) AS total_deaths
FROM RKI_GER_COVID19_DASHBOARD
WHERE (STATE, DISTRICT_TYPE) IN (
  SELECT STATE, DISTRICT_TYPE
  FROM RankedStates
  WHERE rank_by_cases = 1 OR rank_by_deaths = 1
)
GROUP BY STATE, DISTRICT_TYPE;